### ISSUE TITLE
OSDA - low rating

### ISSUE THREAD

**Issue by saakovv** [PaulJerimy/SecCertRoadmapHTML#141]
Hi guys, please tell me, why does the [OSDA](https://www.offsec.com/courses/soc-200/) exam have such a low rating?

This exam (soc 200) according to offsec is a level 200 exam like the same OSCP (pen 200). But at the same time, they occupy different places in the ranking. Although **OSDA is the same OSCP, but only in the world of blue teams.**

And I'll add more:
Just like the person who passed both OSDA and eCTHP (I can send proof if necessary), the gap in the rating between the certificates is confusing.

Thank you and have a nice day.

**Comment by sinecurelife** [comment]
I did not have a lot of data on OSDA so I have a lower confidence for this ranking. I will reevaluate it's placement. Two factors that make it lower than OSCP are:

1) Offensive security certifications are generally seen as more advanced by general reviewers. I would imagine this is due to offensive security borrowing less from other domains and therefore certifications in offensive security take more focused study than equally difficult certifications in say, blue team ops or security management.

2) OSCP has an outsized reputation compared to its actual difficulty. Like CISSP. OSCP is kind of my anchor point for intermediate even though OffSec considers it foundational.

3) Bonus reason: blue ops is crowded and I may have put it one lower just to make it fit. I'm working on that problem too.

I acknowledge my rating system is too subjective and I am working on a more objective/quantitative rating system. There will always be subjectivity though. There will also always be data that I find that some people haven't seen or disagree with. But in general, the current system has worked relatively well.

**Comment by saakovv** [comment]
@sinecurelife 

Thanks a lot for the reply. I got you.
But it's still not clear why there is such a huge difference in rating between OSDA and eCTHP ;)
